name: intellinote
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  file_picker: ^8.0.0
  http: ^1.6.0
  crypto: ^3.0.7
  flutter_markdown: ^0.7.7+1
  flutter_math_fork: ^0.7.4
  markdown: ^7.2.2
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: SimHei
      fonts:
        - asset: assets/fonts/simhei.ttf
    - family: GWMSansUI
      fonts:
        - asset: assets/fonts/GWMSansUI-Regular.ttf
    - family: Consolas
      fonts:
        - asset: assets/fonts/consola.ttf
        - asset: assets/fonts/consolab.ttf
          weight: 700
        - asset: assets/fonts/consolai.ttf
          style: italic
        - asset: assets/fonts/consolaz.ttf
          weight: 700
          style: italic
